
---
- name: download efs and install
  ansible.builtin.command: "wget https://rpmfind.net/linux/opensuse/distribution/leap/15.5/repo/oss/noarch/aws-efs-utils-1.34.5-150100.4.11.1.noarch.rpm -O /tmp/aws-efs-utils.rpm"

- name: Install efs-utils RPM file
  ansible.builtin.yum:
    name: /tmp/aws-efs-utils.rpm
    state: present
    disable_gpg_check: yes
  become: yes
 
- name: Install nfs-utils RPM file
  ansible.builtin.yum:
    name: nfs-utils
    state: present
    disable_gpg_check: yes
  become: yes

- name: Return motd to registered var
  command: ssh-keyscan -t rsa gitlab.shared.valoraws.com >> /root/.ssh/known_hosts