---
dependencies: []

galaxy_info:
  role_name: nvm
  author: "Fran Rodriguez"
  description: NVM installation for Linux
  company: "Devo Inc."
  license: "MIT"
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
      - 6
      - 7
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - precise
      - raring
      - saucy
      - trusty
      - xenial
  galaxy_tags:
    - development
    - web
