---
- name: Import a epel-key from a url
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Download and install epel-release-latest-7 rpm package
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: Import a remi-key from a url
  rpm_key:
    state: present
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi

- name: Download and install remi-release-7 rpm package
  yum:
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

- name: "Install yum-utils"
  yum:
    name: "yum-utils"
    state: present
    lock_timeout: 180

- name: Activate Remi repository as the default repository for php5.6
  ansible.builtin.shell: yum-config-manager --enable remi-php56

- name: "Install PHP5.6 and dependencies"
  yum:
    name:
      - php
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-ldap
      - php-zip
      - php-pdo
      - php-json
      - php-pdo_mysql
    state: present
    lock_timeout: 180
