---
- name: Download and install epel-release-latest-7 rpm package
  yum:
    disable_gpg_check: yes
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: Download and install remi-release-7 rpm package
  yum:
    disable_gpg_check: yes
    name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

- name: "Install yum-utils"
  yum:
    name: "yum-utils"
    state: present
    lock_timeout: 180
    
- name: Activate Remi repository as the default repository for php8.2
  ansible.builtin.shell: sudo yum-config-manager --enable remi-php82

- name: "Install PHP8.2 and dependencies"
  yum:
    name:
      - php
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-ldap
      - php-zip
      - php-pdo
      - php-json
      - php-pdo_mysql
    state: present
    lock_timeout: 180
